name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    permissions:
      contents: write

    strategy:
      matrix:
        os: [macos-15-intel, windows-latest, ubuntu-latest]
        include:
          - os: windows-latest
            arch: x64
            build_command: npx electron-builder --windows --x64 --publish always "-c.publish.repo=dawn-client"
          - os: macos-15-intel
            arch: x64
            build_command: npx electron-builder --mac dmg --x64 --publish always "-c.publish.repo=dawn-client"
          - os: ubuntu-latest
            arch: x64
            build_command: npx electron-builder --linux --x64 --publish always "-c.publish.repo=dawn-client"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install Dependencies
        run: npm install
        env:
          npm_config_arch: x64

      - name: Build and Publish Electron App
        run: ${{ matrix.build_command }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EP_DRAFT: true